### ISSUE TITLE
Android View Problem

### ISSUE THREAD

**Issue by egemenokten** [WrathChaos/react-native-bottom-menu#3]
Half of the bar doesn't appear on Android

![WhatsApp Image 2019-11-02 at 16 40 00](https://user-images.githubusercontent.com/30256104/68071827-94328400-fd8f-11e9-95cd-204b5d15439a.jpeg)

**Comment by WrathChaos** [comment]
This bug is fixed on 
## [Release 0.1.1](https://github.com/WrathChaos/react-native-bottom-menu/releases/tag/0.1.1)
